### ISSUE TITLE
Rewrite pagination definition and include example

### ISSUE THREAD

**Issue by runleonarun** [dbt-labs/dbt-cloud-openapi-spec#44]
Per  an internal conversation, we should update this content. I revised some of the Pagination text:

@GideonShils here are my questions:
* What is the order the results are returned? So we can tell them which ones they are skipping, etc.
* Is there a limit for integer? or is it the number of records minus 1?
~~* The only way I could get this to work is using `?account_id=26712` in addition to `accounts/26712` These feel duplicative. Am I doing something wrong?~~

# Pagination

All top-level API resources support bulk fetches using the "list" or `GET` API methods. These API methods accept `limit` and `offset` query parameters that you can use together to paginate results and return a subset of those results.

* Offsets: Specifies how many records to skip. Can be an integer 0 and higher.
* Limit: Specifies the maximum records you want to retrieve in a single request. Can be an integer up to 100. This limit makes responses easier to handle for servers and people.

## Example request
The following example uses the list projects endpoint to list the projects that your token is authorized to access. This request skips the first 5 projects and lists the next 10 projects. Be sure to replace `<YOUR_TOKEN>` in the Authorization header with your actual API token and YOUR_ACCOUNT_ID with your actual account number.
```
curl --request GET \
  --url 'https://cloud.getdbt.com/api/v3/accounts/YOUR_ACCOUNT_ID/projects/?limit=10&offset=5' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Token <YOUR_TOKEN>'
```

**Comment by GideonShils** [comment]
@runleonarun 
1. order can generally be specified using an `order_by` param, depending on the specific endpoint. By default I believe in most cases we order by the primary key (id)
2. Do you mean is there a limit for `offset`? If so, no, they can offset as far as they want into the list until they get to the end. The only limit is on the actual `limit` parameter
3. That's odd, I was able to send a request with just specifying `accountId` in the route, and _not_ as a query param. What error are you seeing?

**Comment by runleonarun** [comment]
> That's odd, I was able to send a request with just specifying accountId in the route, and not as a query param. What error are you seeing?

False alarm! I must've had it constructed wrong because this works:
```  
 curl --request GET \
  --url 'https://cloud.getdbt.com/api/v3/accounts/26712/projects/?limit=1' \
  --header 'Accept: application/json' \
  --header 'Authorization: Bearer MY_TOKEN
```

**Comment by runleonarun** [comment]
@GideonShils I updated the example and text a little. Feel free to make additional edits.

**Comment by GideonShils** [comment]
@runleonarun looks great! I'll copy this over to the docs site and get a PR up soon 👍🏼

**Comment by GideonShils** [comment]
Will open another PR to add this in the main repo
